message(STATUS "testing")
set(CTEST_PROJECT_NAME standalone)
set(CTEST_SOURCE_DIRECTORY .)
set(CTEST_BINARY_DIRECTORY cibuild)
set(CTEST_CONFIGURATION_TYPE Debug)
# set(CTEST_CMAKE_GENERATOR "Visual Studio 15 2017 Win64")
ctest_start(Experimental)
file(REMOVE_RECURSE ${CTEST_BINARY_DIRECTORY}) 
ctest_configure()
ctest_build()
ctest_test()