name: documentation

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy documentation'
        required: false
        type: boolean


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: 'requirements-dev.txt'
      - name: Install Galatea with dependencies
        run: |
          pip install -r requirements-dev.txt .
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true